### PR TITLE
Enhance serilog implementation

### PR DESCRIPTION
**Pull request by DOMZE**
Enhances the implementation to mimick UseSerilog from Serilog's implementation so that one can configure the loggerConfiguration through code

can obviously be enhanced so that it has UseSerilog's exact logic implementation (keeping Log.Logger or assigning it, etc)

### CODE REVIEW

**Comment by hananiel** [comment]
@DOMZE thanks for the PR, can you go ahead and sign the CLA?

**Comment by DOMZE** [comment]
@hananiel  done

**Comment by hananiel** [comment]
Closing for now, will pull in to the new mono repo.

**Comment by jkonicki** [comment]
@DOMZE Thank you for your patience.  We have been in the process of restructuring the Steeltoe repos.  The PR now needs to conform to the new path of the classes.

**Pull request closed without merging**
